// mt-kit/core/react/src/form/text-input/TextInput.tsx
import React, { useId } from 'react'
import InputLabel from '../InputLabel'
import InputErrorMessage from '../InputErrorMessage'
import Input from '../Input'
import InputHelpText from '../InputHelpText'
import { createInputAriaDescribedby } from '@mattilsynet/designsystem/src/ts/utils'
import { ErrorDetail } from '@mattilsynet/designsystem/src/ts/types'

interface TextInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  /**
   * Label for the TextInput
   */
  label?: string
  /**
   * Text that will be shown below the label
   */
  helpText?: string
  /**
   * Used to show an error message
   */
  errorMessage?: string
  /**
   * Hidden text that comes before the error message for screen readers
   */
  hiddenErrorText?: string
  /**
   * Text that will be shown after the label in parentheses
   */
  textOptional?: string
}

const TextInput: React.FC<TextInputProps> = ({
  label,
  helpText,
  errorMessage,
  hiddenErrorText,
  textOptional,
  required,
  maxLength,
  ...rest
}): JSX.Element => {
  const generatedId = useId()
  const name = 'text-input-' + generatedId
  const errorDetail: ErrorDetail | undefined =
    errorMessage != null ? { key: name, message: errorMessage } : undefined
  const inputAriaDescribedby = createInputAriaDescribedby(
    helpText != null ? name : undefined,
    errorDetail,
    maxLength
  )
  return (
    <>
      <InputLabel htmlFor={name} textOptional={textOptional} isRequired={required}>
        {label}
      </InputLabel>
      <InputHelpText name={name} text={helpText} />
      <InputErrorMessage
        name={name}
        errorMessage={errorMessage}
        hiddenErrorText={hiddenErrorText}
      />
      <Input
        id={name}
        type="text"
        aria-required={required}
        aria-describedby={inputAriaDescribedby}
        aria-invalid={errorMessage != null}
        required={required}
        {...rest}
      />
    </>
  )
}

export default TextInput

// src/svelte/form/TextInput.svelte
<script lang="ts">
  import InputError from './InputErrorMessage.svelte';
  import {countCharacters} from '../../ts/count-characters';
  import type {AutocompleteType, ErrorDetail, InputModeType} from '../../ts/types';
  import {createInputAriaDescribedby} from '../../ts/utils';
  import Label from './Label.svelte';

  export let value;
  export let name: string;
  export let label: string;
  export let error: ErrorDetail | undefined;
  export let helpText: string | undefined;
  export let textOptional: string | undefined;
  export let hiddenErrorText: string | undefined;

  export let maxlength: number | undefined;
  export let placeholder: string | undefined;
  export let isRequired: boolean | undefined = undefined;
  export let inputmode: InputModeType | undefined;
  export let autocomplete: AutocompleteType | undefined;
</script>

<Label htmlFor={name} {isRequired} {textOptional}>{label}</Label>

{#if helpText}
  <div id={`${name}-hint`} class="hint">
    {@html helpText}
  </div>
{/if}

{#if error}
  <InputError {...error} {hiddenErrorText} />
{/if}

<input
  id={name}
  {name}
  use:countCharacters
  class="form-field"
  bind:value
  class:error
  aria-required={isRequired || undefined}
  aria-describedby={createInputAriaDescribedby(name, error)}
  aria-invalid={!!error}
  {maxlength}
  {inputmode}
  {placeholder}
  {autocomplete}
/>
