// mt-kit/core/svelte/src/lib/svelte/components/form/InputErrorMessage.svelte
<script lang="ts">
  export let key: string
  export let message: string
  export let hiddenErrorText = 'Feilmelding'
  let className = ''
  export { className as class }
</script>

<span id={`${key}-error`} class="form-error {className}">
  <span class="inclusively-hidden">{hiddenErrorText}:</span>
  {message}
</span>

// mt-kit/core/react/src/form/InputErrorMessage.tsx
import React from 'react'

interface InputErrorMessageProps {
  name: string
  errorMessage?: string
  hiddenErrorText?: string
}

const InputErrorMessage: React.FC<InputErrorMessageProps> = ({
  name,
  errorMessage,
  hiddenErrorText = 'Feilmelding'
}): JSX.Element | null => {
  if (errorMessage != null) {
    return (
      <span id={`${name}-error`} className="form-error">
        <span className="inclusively-hidden">{hiddenErrorText}:</span>
        {errorMessage}
      </span>
    )
  } else {
    return null
  }
}

export default InputErrorMessage
